


# TODO's!
# 
#  1) LOAD BERT MODEL
#  2) TOPIC MODEL THE USER PROMPT USING THIS MODEL TO GENEREATE A TOPIC NUMBER    ---- (A)
#  3) CREATE A SUMMARY OF THE USER PROMPT
#  4) CREATE A SENTIMENT OF THE USER PROMPT
#  
#  RAG STUFF
# 
#  PART 1
#
#  5) USE THE TOPIC MODEL NUMBER FROM (A) TO QUERY THE 'data/topic_modelled_database/test_data.csv'
#  6) USE ANGUS SQL SCRIPT TO GET TOP 3 THERAPIST RESPONSES FOR THE USER PROMPT
# 
#  PART 2
#
#  7) USE THE TIME SERIES DATA TO GET THE SENTIMENT, TOPIC AND SUMMARY OF LAST 5 DAYS OF USER PROMPT
#
#  8) COMBINE PART 1 AND PART 2 TO GENEREATE A BIG PROMPT
#
#  9) PASS INTO THE LLM MODEL TO GENERATE A RESPONSE